DATASET_DIR = "../datasets"  # 데이터셋 경로

ITEMS = {
    "item1": ["ITEM 1.", "BUSINESS"],
    "item1a": ["ITEM 1A.", "RISK FACTORS"],
    "item7": ["ITEM 7.", "MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL CONDITION AND RESULTS OF OPERATIONS"],
    "income_statement": ["ITEM 15.", "EXHIBITS AND FINANCIAL STATEMENT SCHEDULES"]
}

INDEX_INFO = [
    "ITEM 1. BUSINESS", "ITEM 1A. RISK FACTORS", "ITEM 1B. UNRESOLVED STAFF COMMENTS",
    "ITEM 2.", "ITEM 3.", "ITEM 4.", "ITEM 5.", "ITEM 6.",
    "ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL CONDITION AND RESULTS OF OPERATIONS",
    "ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSURES ABOUT MARKET RISK", "ITEM 8.",
    "ITEM 9.", "ITEM 9A.", "ITEM 9B.", "ITEM 15. EXHIBITS AND FINANCIAL STATEMENT SCHEDULES"
]
